#!/usr/bin/env python3
"""Generate src/webui_assets.h from webui/ source files.

Reads each file in webui/, gzip-compresses text assets (.html, .css, .js),
and writes a C header with byte arrays and a lookup table.

JavaScript modules under webui/js/ are concatenated in dependency order
into a single IIFE blob (equivalent to the old monolithic app.js).

Usage:
    python3 tools/gen_webui.py
"""

import gzip
import os
import sys

WEBUI_DIR = os.path.join(os.path.dirname(__file__), '..', 'webui')
OUTPUT = os.path.join(os.path.dirname(__file__), '..', 'src', 'webui_assets.h')

# JS modules concatenated in dependency order into app.js
JS_MODULES = [
	'js/core.js',
	'js/format.js',
	'js/connection.js',
	'js/settings.js',
	'js/overlay.js',
	'js/groups.js',
	'js/chart.js',
	'js/monitor.js',
	'js/devices.js',
	'js/tabs.js',
	'js/debug.js',
	'js/init.js',
]

ASSETS = [
	{
		'file': 'index.html',
		'uri': '/',
		'var': 'webui_index_html',
		'mime': 'text/html; charset=utf-8',
		'gzip': True,
	},
	{
		'file': 'app.css',
		'uri': '/app.css',
		'var': 'webui_app_css',
		'mime': 'text/css; charset=utf-8',
		'gzip': True,
	},
	{
		'file': '__app_js__',  # placeholder — built from JS_MODULES
		'uri': '/app.js',
		'var': 'webui_app_js',
		'mime': 'application/javascript; charset=utf-8',
		'gzip': True,
	},
	{
		'file': 'favicon.ico',
		'uri': '/favicon.ico',
		'var': 'webui_favicon_ico',
		'mime': 'image/x-icon',
		'gzip': False,
	},
]


def concat_js_modules(webui_dir):
	"""Concatenate JS modules into a single IIFE string."""
	parts = []
	parts.append('(function () {')
	parts.append("'use strict';")
	total_lines = 0

	for mod in JS_MODULES:
		filepath = os.path.join(webui_dir, mod)
		if not os.path.exists(filepath):
			print('WARNING: %s not found, skipping' % filepath,
				file=sys.stderr)
			continue

		with open(filepath, 'r', encoding='utf-8', newline='') as f:
			content = f.read()

		# Strip trailing whitespace but preserve content
		content = content.rstrip()
		lines = content.count('\n') + 1
		total_lines += lines
		print('  %-20s %5d lines  %6d bytes' % (mod, lines, len(content)))

		parts.append('')
		parts.append('// ---- %s ----' % os.path.basename(mod))
		parts.append(content)

	parts.append('')
	parts.append('})();')
	parts.append('')

	blob = '\n'.join(parts)
	print('  %-20s %5d lines  %6d bytes (concatenated)' % (
		'TOTAL', total_lines, len(blob)))
	return blob


def to_c_array(data, var_name):
	"""Convert bytes to a C static const unsigned char array."""
	lines = []
	lines.append('static const unsigned char %s[] = {' % var_name)
	for i in range(0, len(data), 16):
		chunk = data[i:i + 16]
		hex_vals = ', '.join('0x%02x' % b for b in chunk)
		lines.append('\t' + hex_vals + ',')
	lines.append('};')
	return '\n'.join(lines)


def main():
	webui_dir = os.path.normpath(WEBUI_DIR)
	output_path = os.path.normpath(OUTPUT)

	# Pre-build concatenated JS
	print('Concatenating JS modules:')
	js_blob = concat_js_modules(webui_dir)
	js_raw = js_blob.encode('utf-8')

	parts = []
	parts.append('/* Auto-generated by tools/gen_webui.py -- DO NOT EDIT */')
	parts.append('')
	parts.append('#ifndef INCLUDE_WEBUI_ASSETS_H_')
	parts.append('#define INCLUDE_WEBUI_ASSETS_H_')
	parts.append('')

	total_raw = 0
	total_out = 0

	for asset in ASSETS:
		if asset['file'] == '__app_js__':
			# Use pre-built concatenated JS
			raw = js_raw
		else:
			filepath = os.path.join(webui_dir, asset['file'])
			if not os.path.exists(filepath):
				print('WARNING: %s not found, skipping' % filepath,
					file=sys.stderr)
				continue

			with open(filepath, 'rb') as f:
				raw = f.read()

		if asset['gzip']:
			data = gzip.compress(raw, compresslevel=9)
		else:
			data = raw

		total_raw += len(raw)
		total_out += len(data)

		label = 'app.js' if asset['file'] == '__app_js__' else asset['file']
		print('%s: %d bytes raw, %d bytes %s' % (
			label, len(raw), len(data),
			'gzipped' if asset['gzip'] else 'raw'))

		parts.append(to_c_array(data, asset['var']))
		parts.append('')

	print('TOTAL: %d bytes raw, %d bytes embedded (%.1f%% of raw)' % (
		total_raw, total_out, 100.0 * total_out / total_raw if total_raw else 0))

	# Lookup table struct and array
	parts.append('typedef struct {')
	parts.append('\tconst char *uri;')
	parts.append('\tconst unsigned char *data;')
	parts.append('\tunsigned int size;')
	parts.append('\tconst char *mime_type;')
	parts.append('\tint is_gzipped;')
	parts.append('} webui_asset_t;')
	parts.append('')
	parts.append('static const webui_asset_t webui_assets[] = {')
	for asset in ASSETS:
		if asset['file'] != '__app_js__':
			filepath = os.path.join(webui_dir, asset['file'])
			if not os.path.exists(filepath):
				continue
		parts.append('\t{"%s", %s, sizeof(%s), "%s", %d},' % (
			asset['uri'], asset['var'], asset['var'],
			asset['mime'], 1 if asset['gzip'] else 0))
	parts.append('\t{NULL, NULL, 0, NULL, 0}')
	parts.append('};')
	parts.append('')
	parts.append('#endif /* INCLUDE_WEBUI_ASSETS_H_ */')
	parts.append('')

	with open(output_path, 'w', newline='\n') as f:
		f.write('\n'.join(parts))

	print('Generated %s' % output_path)


if __name__ == '__main__':
	main()
